@url = http://localhost:5000/invoices-module
@invoiceId = 1549a735-58b4-4220-99fb-3930f877d3ee

@Euro = 1
@PLN = 2

### Add invoice
POST {{url}}/invoices
Content-Type: application/json

{
    "type": "FV",
    "number": "08/04/2021",
    "buyerId": "ed672616-4b17-4e33-8733-b6d13893f156",
    "sellerId": "584aa75c-9d50-41f9-ac94-890ad2243a44",
    "dateOfIssue": "2021-04-20",
    "saleDate": "2021-04-20",
   
    "items": [
        {
            "name": "Usługa informatyczna",
            "unit": "Piece",
            "amount": 20,
            "netPrice": 120,
            "vatRate": 23,
            "currency": {{PLN}},
            "exchangeRate": 4.5474
        }
    ]
}

### Get invoices
GET {{url}}/invoices

### Get invoice
GET {{url}}/invoices/{{invoiceId}}

### Update invoice
PUT {{url}}/invoices/{{invoiceId}}
Content-Type: application/json

{
    "type": "FV",
    "number": "15/12/2021",
    "buyerId": "ed672616-4b17-4e33-8733-b6d13893f156",
    "sellerId": "584aa75c-9d50-41f9-ac94-890ad2243a44",
    "dateOfIssue": "2021-12-16",
    "saleDate": "2021-12-16"
}

### Delete invoice
DELETE {{url}}/invoices/{{invoiceId}}